### ISSUE TITLE
Reset stats button

### ISSUE THREAD

**Issue by adamk33n3r** [LoyalFTW/CrossGambling#5]
We just had an issue tonight in our guild where someone clicked the reset stats button and it cleared out all of our stats. He was expecting it to only clear *his* stats, not literally everyone in the group. I looked through the code and it definitely looks intended (since it's sent as an addon event) but I'm not sure what the use case is, especially unprompted. I don't want someone to be able to just join my group and reset my stats, ya know? I'm not sure what your intentions were with that functionality, but I think it could be revisited.

**Comment by LoyalFTW** [comment]
Sorry about that I do all my testing by myself and must of some how missed that when I redid functions. 

You might still be able to get your stats back in ur WTF -> Account -> (account number) -> SavedVariables -> CrossGambling.lua.bak 

Might be gone by now though since I am 2 days late. But never hurts to check.

**Comment by LoyalFTW** [comment]
Just did an update and changed it to a normal function instead of an event function. All should be working fine now.

**Comment by adamk33n3r** [comment]
@LoyalFTW we did actually recover some of our stats using the backup that night. It didn't include that night's session, but was better than nothing! :)
